turtlebot2: #namespace
    task_and_robot_environment_name: 'MyTurtleBot2Empty-v0'  # MyTurtleBot2Wall-v0
    ros_ws_abspath: "/home/tammy/leader_follower_ws"
#    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 1.0 # 0.9
    epsilon_discount: 0.999
    nepisodes: 2000
    nsteps: 10000
    running_step: 0.06 #0.06 # Time for each step
